:wmname: heawm
= {wmname}
:toc:

{wmname} is a keyboard-centric‌footnote:[No, no, not like others… this one
is really.], semidynamic tiling window manager for the X Window System with
multihead‌footnote:[Here be dragons.],
multihand‌footnote:[Stuff that requires at least three limbs:
multi-pointer and friends. Not for introverts. You have been warned.],
multi-leg‌footnote:[This program is so much crap you will surely use both
of your legs.] support, aiming to provide O(1) navigation.

- Configure in C with some X resources.
- Minimal ICCCM and NetWM support--mainly because they are useless and/or against the concept.
- Script by sending messages to root.

== Philosophy

* Enjoy the *weightlessness*.
+
Here there is no up or down, left or right. You travel from one window to
another through wormholes.

* _“That’s one small step for other window managers, *one giant leap* for `{wmname}`.”_
+
Nothing takes more than 2 keystrokes.

* Solid black *wallpapers are nice* for one instant. Every pixel wants to be a useful pixel, so do not make them sad.

* What you see is what you get. There is only one layout–grid– (but you do not
  even have to know about it) that can be easily managed.
  Internally, they are called “boxes.” Every box can contain infinite, nicely
  arranged boxes. Your window will be in the last box.

== Installation

You will need the following tools and libraries.

=== Dependencies

* `cc -std=c11`
* `make`
* `xcb{,-cursor,-keysyms,-shape,-xinput,-xrm}`
* `xcb-util` ^*^
* `xcb-icccm` ^**^
* `cairo`

^*^: Debug build.
^**^: Headers only.

=== Compiling from source

[source,sh,subs=+attributes]
----
git clone https://github.com/zsugabubus/{wmname} &&
cd {wmname} &&
make &&
make install
----

== Usage

`man {wmname}`.
