:wmname: heawm
= {wmname}
:toc:

Lightweight, keyboard-centric‌footnote:[No, no, not like others… this one is
really.], infinitely nestable, primitive semi-automatic‌footnote:[WTF!?] tiling
window manager for X Window System with multi-head‌footnote:[Here be dragons.],
multi-hand‌footnote:[Stuff that requires at least three limbs: multi-pointer
and friends. Not for introverts. You have been warned.],
multi-leg‌footnote:[Now you can kick your computer with both of your legs.] support‌footnote:[That’s actually a
lie.]. Infinite possibilities, single layout. Replace all windows on all
monitors at once for better separating different kinds of work.

Configuration currently happens in C in a compile yourself manner. Comes with
sane defaults.

== Philosophy

* Enjoy the *weightlessness*. Here there is no up or down, left or right. You
  travel from one window to another through wormholes.
* “That’s one small step for other window managers, *one giant leap* for `{wmname}`.”—nobody Nothing takes more than 2 keystrokes.
* Solid black *wallpapers are nice* for one instant. Every pixel wants to be a useful pixel, so do not make them sad.
* What you see is what you get. There is only one layout–grid– (but you do not
  even have to know about it) that can be easily managed.
  Internally, they are called “boxes.” Every box can contain infinite, nicely
  arranged boxes. Your window will be in the last box.

== Installation

=== Dependencies

X server with X Input Extension 2 support.

* `cc -std=c11`
* `make`
* `xcb{,-cursor,-keysyms,-shape,-util,-xinput}`
* `cairo`

=== Compiling from source

[source,sh,subs=+attributes]
----
git clone https://github.com/zsugabubus/{wmname} &&
cd {wmname} &&
make &&
make install # <1>
----

<1> Or use `make xephyr && make run` if you want to give it a try first.
