:wmname: heawm
= {wmname}
:toc:

{wmname} is a keyboard-centric‌footnote:[No, no, not like others… this one
is really.], semidynamic tiling window manager for the X Window System with
multihead‌footnote:[Here be dragons.],
multihand‌footnote:[Stuff that requires at least three limbs:
multi-pointer and friends. Not for introverts. You have been warned.],
multi-leg‌footnote:[This program is so much crap you will surely use both
of your legs.] support, aiming to provide O(1) navigation.

- Configure in C with some basic X resources.
- Minimal ICCCM and NetWM support--mainly because they are useless and/or against the concept.
- Script by sending messages to root.

== Philosophy

* Enjoy the *weightlessness*.
+
Here there is no up or down, left or right. You travel from one window to
another through higher dimensions.

* _“That’s one small step for other window managers, *one giant leap* for `{wmname}`.”_
+
Nothing takes more than a few keystrokes.

* Solid black *wallpapers are nice*.
+
Every pixel wants to be a useful pixel.

== Installation

You will need the following tools and libraries.

=== Dependencies

* `cc -std=c11`
* `make`
* `xcb{,-cursor,-keysyms,-shape,-xfixes,-xinput,-xrm}`
* `xcb-util` (Debug build.)
* `xcb-icccm` (Headers only.)
* `cairo`

=== Compiling from source

[source,sh,subs=+attributes]
----
git clone https://github.com/zsugabubus/{wmname} &&
cd {wmname} &&
make &&
make install
----

== Usage

`man {wmname}`.
